/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecruiterRouteImport } from './routes/recruiter'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecruiterIndexRouteImport } from './routes/recruiter.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as RecruiterSettingsRouteImport } from './routes/recruiter.settings'
import { Route as RecruiterJobsRouteImport } from './routes/recruiter.jobs'
import { Route as RecruiterInterviewsRouteImport } from './routes/recruiter.interviews'
import { Route as RecruiterCandidatesRouteImport } from './routes/recruiter.candidates'
import { Route as RecruiterAssessmentsRouteImport } from './routes/recruiter.assessments'
import { Route as RecruiterAnalyticsRouteImport } from './routes/recruiter.analytics'
import { Route as AppSavedRouteImport } from './routes/app.saved'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppLearningRouteImport } from './routes/app.learning'
import { Route as AppInterviewRouteImport } from './routes/app.interview'
import { Route as AppDiscoverRouteImport } from './routes/app.discover'
import { Route as AppCommunityRouteImport } from './routes/app.community'
import { Route as AppApplicationsRouteImport } from './routes/app.applications'
import { Route as AppJobsIdRouteImport } from './routes/app.jobs.$id'

const RecruiterRoute = RecruiterRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterIndexRoute = RecruiterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecruiterRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const RecruiterSettingsRoute = RecruiterSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterJobsRoute = RecruiterJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterInterviewsRoute = RecruiterInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterCandidatesRoute = RecruiterCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterAssessmentsRoute = RecruiterAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterAnalyticsRoute = RecruiterAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => RecruiterRoute,
} as any)
const AppSavedRoute = AppSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppLearningRoute = AppLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewRoute = AppInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsRoute = AppApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsIdRoute = AppJobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/recruiter': typeof RecruiterRouteWithChildren
  '/app/applications': typeof AppApplicationsRoute
  '/app/community': typeof AppCommunityRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/interview': typeof AppInterviewRoute
  '/app/learning': typeof AppLearningRoute
  '/app/profile': typeof AppProfileRoute
  '/app/saved': typeof AppSavedRoute
  '/recruiter/analytics': typeof RecruiterAnalyticsRoute
  '/recruiter/assessments': typeof RecruiterAssessmentsRoute
  '/recruiter/candidates': typeof RecruiterCandidatesRoute
  '/recruiter/interviews': typeof RecruiterInterviewsRoute
  '/recruiter/jobs': typeof RecruiterJobsRoute
  '/recruiter/settings': typeof RecruiterSettingsRoute
  '/app/': typeof AppIndexRoute
  '/recruiter/': typeof RecruiterIndexRoute
  '/app/jobs/$id': typeof AppJobsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/app/applications': typeof AppApplicationsRoute
  '/app/community': typeof AppCommunityRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/interview': typeof AppInterviewRoute
  '/app/learning': typeof AppLearningRoute
  '/app/profile': typeof AppProfileRoute
  '/app/saved': typeof AppSavedRoute
  '/recruiter/analytics': typeof RecruiterAnalyticsRoute
  '/recruiter/assessments': typeof RecruiterAssessmentsRoute
  '/recruiter/candidates': typeof RecruiterCandidatesRoute
  '/recruiter/interviews': typeof RecruiterInterviewsRoute
  '/recruiter/jobs': typeof RecruiterJobsRoute
  '/recruiter/settings': typeof RecruiterSettingsRoute
  '/app': typeof AppIndexRoute
  '/recruiter': typeof RecruiterIndexRoute
  '/app/jobs/$id': typeof AppJobsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/recruiter': typeof RecruiterRouteWithChildren
  '/app/applications': typeof AppApplicationsRoute
  '/app/community': typeof AppCommunityRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/interview': typeof AppInterviewRoute
  '/app/learning': typeof AppLearningRoute
  '/app/profile': typeof AppProfileRoute
  '/app/saved': typeof AppSavedRoute
  '/recruiter/analytics': typeof RecruiterAnalyticsRoute
  '/recruiter/assessments': typeof RecruiterAssessmentsRoute
  '/recruiter/candidates': typeof RecruiterCandidatesRoute
  '/recruiter/interviews': typeof RecruiterInterviewsRoute
  '/recruiter/jobs': typeof RecruiterJobsRoute
  '/recruiter/settings': typeof RecruiterSettingsRoute
  '/app/': typeof AppIndexRoute
  '/recruiter/': typeof RecruiterIndexRoute
  '/app/jobs/$id': typeof AppJobsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/onboarding'
    | '/recruiter'
    | '/app/applications'
    | '/app/community'
    | '/app/discover'
    | '/app/interview'
    | '/app/learning'
    | '/app/profile'
    | '/app/saved'
    | '/recruiter/analytics'
    | '/recruiter/assessments'
    | '/recruiter/candidates'
    | '/recruiter/interviews'
    | '/recruiter/jobs'
    | '/recruiter/settings'
    | '/app/'
    | '/recruiter/'
    | '/app/jobs/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/app/applications'
    | '/app/community'
    | '/app/discover'
    | '/app/interview'
    | '/app/learning'
    | '/app/profile'
    | '/app/saved'
    | '/recruiter/analytics'
    | '/recruiter/assessments'
    | '/recruiter/candidates'
    | '/recruiter/interviews'
    | '/recruiter/jobs'
    | '/recruiter/settings'
    | '/app'
    | '/recruiter'
    | '/app/jobs/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/onboarding'
    | '/recruiter'
    | '/app/applications'
    | '/app/community'
    | '/app/discover'
    | '/app/interview'
    | '/app/learning'
    | '/app/profile'
    | '/app/saved'
    | '/recruiter/analytics'
    | '/recruiter/assessments'
    | '/recruiter/candidates'
    | '/recruiter/interviews'
    | '/recruiter/jobs'
    | '/recruiter/settings'
    | '/app/'
    | '/recruiter/'
    | '/app/jobs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  RecruiterRoute: typeof RecruiterRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recruiter': {
      id: '/recruiter'
      path: '/recruiter'
      fullPath: '/recruiter'
      preLoaderRoute: typeof RecruiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/': {
      id: '/recruiter/'
      path: '/'
      fullPath: '/recruiter/'
      preLoaderRoute: typeof RecruiterIndexRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/recruiter/settings': {
      id: '/recruiter/settings'
      path: '/settings'
      fullPath: '/recruiter/settings'
      preLoaderRoute: typeof RecruiterSettingsRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/jobs': {
      id: '/recruiter/jobs'
      path: '/jobs'
      fullPath: '/recruiter/jobs'
      preLoaderRoute: typeof RecruiterJobsRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/interviews': {
      id: '/recruiter/interviews'
      path: '/interviews'
      fullPath: '/recruiter/interviews'
      preLoaderRoute: typeof RecruiterInterviewsRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/candidates': {
      id: '/recruiter/candidates'
      path: '/candidates'
      fullPath: '/recruiter/candidates'
      preLoaderRoute: typeof RecruiterCandidatesRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/assessments': {
      id: '/recruiter/assessments'
      path: '/assessments'
      fullPath: '/recruiter/assessments'
      preLoaderRoute: typeof RecruiterAssessmentsRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/analytics': {
      id: '/recruiter/analytics'
      path: '/analytics'
      fullPath: '/recruiter/analytics'
      preLoaderRoute: typeof RecruiterAnalyticsRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/app/saved': {
      id: '/app/saved'
      path: '/saved'
      fullPath: '/app/saved'
      preLoaderRoute: typeof AppSavedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/learning': {
      id: '/app/learning'
      path: '/learning'
      fullPath: '/app/learning'
      preLoaderRoute: typeof AppLearningRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/interview': {
      id: '/app/interview'
      path: '/interview'
      fullPath: '/app/interview'
      preLoaderRoute: typeof AppInterviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/discover': {
      id: '/app/discover'
      path: '/discover'
      fullPath: '/app/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/community': {
      id: '/app/community'
      path: '/community'
      fullPath: '/app/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/applications': {
      id: '/app/applications'
      path: '/applications'
      fullPath: '/app/applications'
      preLoaderRoute: typeof AppApplicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/jobs/$id': {
      id: '/app/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/app/jobs/$id'
      preLoaderRoute: typeof AppJobsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppApplicationsRoute: typeof AppApplicationsRoute
  AppCommunityRoute: typeof AppCommunityRoute
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppInterviewRoute: typeof AppInterviewRoute
  AppLearningRoute: typeof AppLearningRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSavedRoute: typeof AppSavedRoute
  AppIndexRoute: typeof AppIndexRoute
  AppJobsIdRoute: typeof AppJobsIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApplicationsRoute: AppApplicationsRoute,
  AppCommunityRoute: AppCommunityRoute,
  AppDiscoverRoute: AppDiscoverRoute,
  AppInterviewRoute: AppInterviewRoute,
  AppLearningRoute: AppLearningRoute,
  AppProfileRoute: AppProfileRoute,
  AppSavedRoute: AppSavedRoute,
  AppIndexRoute: AppIndexRoute,
  AppJobsIdRoute: AppJobsIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface RecruiterRouteChildren {
  RecruiterAnalyticsRoute: typeof RecruiterAnalyticsRoute
  RecruiterAssessmentsRoute: typeof RecruiterAssessmentsRoute
  RecruiterCandidatesRoute: typeof RecruiterCandidatesRoute
  RecruiterInterviewsRoute: typeof RecruiterInterviewsRoute
  RecruiterJobsRoute: typeof RecruiterJobsRoute
  RecruiterSettingsRoute: typeof RecruiterSettingsRoute
  RecruiterIndexRoute: typeof RecruiterIndexRoute
}

const RecruiterRouteChildren: RecruiterRouteChildren = {
  RecruiterAnalyticsRoute: RecruiterAnalyticsRoute,
  RecruiterAssessmentsRoute: RecruiterAssessmentsRoute,
  RecruiterCandidatesRoute: RecruiterCandidatesRoute,
  RecruiterInterviewsRoute: RecruiterInterviewsRoute,
  RecruiterJobsRoute: RecruiterJobsRoute,
  RecruiterSettingsRoute: RecruiterSettingsRoute,
  RecruiterIndexRoute: RecruiterIndexRoute,
}

const RecruiterRouteWithChildren = RecruiterRoute._addFileChildren(
  RecruiterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  RecruiterRoute: RecruiterRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
